### ISSUE TITLE
allow ocaml -> reason from .re file

### ISSUE THREAD

**Issue by bassjacob** [reasonml-editor/atom-reason-refmt#1]
Hi :),

There's a workflow I've been following where I can convert ocaml code from inside a reason file. Would you be open to defining the conversion functions like so?

```javascript
disposables.add(atom.commands.add(
  'atom-text-editor[data-grammar="source reason"], atom-text-editor[data-grammar="source ocaml"]', {
    'reason-refmt:format': () => format(),
    'reason-refmt:convert-to-ocaml': () => convertToOCaml()
    'reason-refmt:convert-to-reason': () => convertToReason()
  }
))
```

I'd be happy to open a PR if you're happy with that idea?

**Comment by 314eter** [comment]
I assume this conversion has to happen in-place, and not in a new file, as is currently the case? PR's are always welcome.

**Comment by bassjacob** [comment]
@314eter correct, I'd highlight an ocaml expression, run the convert command and convert it in place. I'll open a PR tonight :smile:
