### ISSUE TITLE
Chatty syntax errors

### ISSUE THREAD

**Issue by whmountains** [reasonml-editor/atom-reason-refmt#8]
![screen shot 2017-09-12 at 12 17 30 pm](https://user-images.githubusercontent.com/8680147/30333889-0a9ba708-97ac-11e7-8bca-408f6b433866.png)

This happens whenever I hesitate while typing and there happens to be a syntax error.

My linter warns me about syntax errors, so I don't need yellow messages popping up as well.  Could there at least be a config option to turn these annoying messages off?

**Comment by nwaywood** [comment]
I think the proper way to fix this is for the plugin to expose an option to set `silent=true`. However in the meantime I fixed this by manually setting `silent=true` here https://github.com/reasonml-editor/atom-reason-refmt/blob/master/lib/main.js#L53
